kafka:
  bootstrap_servers: localhost:9092
  group_id: consumer-group
  topics: ""
  map:
    sku-atualizado: "com.example.consumer.commands.SkuCommand"
    sku-lojista-atualizado: "com.example.consumer.commands.SkuLojistaCommand"
  producerMap:
    TOPICSKUID: "sku-id-atualizado"

javamelody:
  management-endpoint-monitoring-enabled: false
  # Enable JavaMelody auto-configuration (optional, default: true)
  enabled: false
  # Data source names to exclude from monitoring (optional, comma-separated)
  excluded-datasources: secretSource,topSecretSource
  # Enable monitoring of Spring services and controllers (optional, default: true)
  spring-monitoring-enabled: false
  # Initialization parameters for JavaMelody (optional)
  # See: https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
  # to add basic auth:
  authorized-users: admin:admin
  init-parameters:
    # log http requests:
    log: true
    # to exclude images, css, fonts and js urls from the monitoring:
    #url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)
    # to aggregate digits in http requests:
    #http-transform-pattern: \d+
    # to add basic auth:
    #authorized-users: admin:pwd
    # to change the default storage directory:
    #storage-directory: /tmp/javamelody
    # to change the default "/monitoring" path:
    #monitoring-path: /admin/performance

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: refresh, mappings, httptrace, metrics, heapdump, loggers, info, env, logfile, health, configprops, routes, hystrix.stream, monitoring
    enabled-by-default: true
  endpoint:
    health:
      show-details: always